blank_issues_enabled: false
contact_links:
  - name: Ask a question
    about: Ask questions and discuss with other users of the library.
    url: https://discord.gg/gJDbCw8aQy
  - name: Discord Server
    about: Use our official Discord server to ask for help and questions as well.
    url: https://discord.gg/gJDbCw8aQy
